In [1]:
# This command installs mlxtend.
%pip install mlxtend --upgrade

Requirement already satisfied: mlxtend in c:\users\diku3\appdata\local\programs\python\python39\lib\site-packages (0.19.0)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: setuptools in c:\users\diku3\appdata\roaming\python\python39\site-packages (from mlxtend) (58.5.3)
Requirement already satisfied: scipy>=1.2.1 in c:\users\diku3\appdata\local\programs\python\python39\lib\site-packages (from mlxtend) (1.7.1)
Requirement already satisfied: pandas>=0.24.2 in c:\users\diku3\appdata\roaming\python\python39\site-packages (from mlxtend) (1.3.4)
Requirement already satisfied: numpy>=1.16.2 in c:\users\diku3\appdata\roaming\python\python39\site-packages (from mlxtend) (1.21.4)
Requirement already satisfied: joblib>=0.13.2 in c:\users\diku3\appdata\local\programs\python\python39\lib\site-packages (from mlxtend) (1.0.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\diku3\appdata\local\programs\python\python39\lib\site-packages (from mlxtend) (3.4.3)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\diku3\appdata\roaming\python\python39\site-packages (from mlxtend) (1.0.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\diku3\appdata\roaming\python\python39\site-packages (from matplotlib>=3.0.0->mlxtend) (8.4.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\diku3\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\diku3\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\diku3\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\diku3\appdata\roaming\python\python39\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\diku3\appdata\roaming\python\python39\site-packages (from pandas>=0.24.2->mlxtend) (2021.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\diku3\appdata\roaming\python\python39\site-packages (from scikit-learn>=0.20.3->mlxtend) (3.0.0)
Requirement already satisfied: six>=1.5 in c:\users\diku3\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

WARNING: You are using pip version 21.3.1; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Users\diku3\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [2]:
# Importing the pandas library, mlxtend.preprocessing, mlxtend.frequent_patterns.
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder 
from mlxtend.frequent_patterns import association_rules
from mlxtend.frequent_patterns import fpgrowth

In [3]:
# Creating a dataframe with the columns as the unique values in the dataset.
dataset = [['TFIOS', '5 feet apart', 'Walk to remember'], ['TFIOS', 'Walk to remember'],
['Divergent', 'Harry Potter','Walk to remember'], ['TFIOS', 'Five feet apart'],
['Divergent','Harry Potter']] 
te = TransactionEncoder()
te_array = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_array, columns=te.columns_)

In [4]:
df

,5 feet apart,Divergent,Five feet apart,Harry Potter,TFIOS,Walk to remember
0,True,False,False,False,True,True
1,False,False,False,False,True,True
2,False,True,False,True,False,True
3,False,False,True,False,True,False
4,False,True,False,True,False,False

In [5]:
# Using the fpgrowth algorithm to find frequent itemsets. returns support and itemset
frequent_itemsets_fp=fpgrowth(df, min_support=0.02, use_colnames=True)

In [6]:
# A list of frequent itemsets.
frequent_itemsets_fp

    support                                     itemsets
0       0.6                           (Walk to remember)
1       0.6                                      (TFIOS)
2       0.2                               (5 feet apart)
3       0.4                               (Harry Potter)
4       0.4                                  (Divergent)
5       0.2                            (Five feet apart)
6       0.4                    (Walk to remember, TFIOS)
7       0.2                        (TFIOS, 5 feet apart)
8       0.2             (Walk to remember, 5 feet apart)
9       0.2      (Walk to remember, TFIOS, 5 feet apart)
10      0.2             (Walk to remember, Harry Potter)
11      0.4                    (Divergent, Harry Potter)
12      0.2                (Walk to remember, Divergent)
13      0.2  (Walk to remember, Divergent, Harry Potter)
14      0.2                     (Five feet apart, TFIOS)

In [7]:
# Using the frequent itemsets to find rules that have a confidence of at least 80% returns dataframe
rules_fp = association_rules(frequent_itemsets_fp, metric="confidence", min_threshold=0.8)

In [8]:
rules_fp

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(5 feet apart),(TFIOS),0.2,0.6,0.2,1.0,1.666667,0.08,inf
1,(5 feet apart),(Walk to remember),0.2,0.6,0.2,1.0,1.666667,0.08,inf
2,"(Walk to remember, 5 feet apart)",(TFIOS),0.2,0.6,0.2,1.0,1.666667,0.08,inf
3,"(TFIOS, 5 feet apart)",(Walk to remember),0.2,0.6,0.2,1.0,1.666667,0.08,inf
4,(5 feet apart),"(Walk to remember, TFIOS)",0.2,0.4,0.2,1.0,2.500000,0.12,inf
5,(Divergent),(Harry Potter),0.4,0.4,0.4,1.0,2.500000,0.24,inf
6,(Harry Potter),(Divergent),0.4,0.4,0.4,1.0,2.500000,0.24,inf
7,"(Walk to remember, Divergent)",(Harry Potter),0.2,0.4,0.2,1.0,2.500000,0.12,inf
8,"(Walk to remember, Harry Potter)",(Divergent),0.2,0.4,0.2,1.0,2.500000,0.12,inf
9,(Five feet apart),(TFIOS),0.2,0.6,0.2,1.0,1.666667,0.08,inf