## PCA

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("iris.csv")

In [3]:
# Import PCA from sklearn
from sklearn.decomposition import PCA

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
data_PCA = df.iloc[:,1:5]

In [6]:
y1 = pd.DataFrame(df["Species"], columns=["Species"])

In [7]:
# n_components=2

# Instantiate PCA
pca = PCA(n_components=2)

# Fit PCA to features
principalComponents = pca.fit_transform(data_PCA)

df = pd.DataFrame(data = principalComponents, 
                  columns = ['PC1','PC2'])

target = pd.Series(y1['Species'], name='Species')

result_df = pd.concat([df, target], axis=1)
result_df

          PC1       PC2         Species
0   -2.684207  0.326607     Iris-setosa
1   -2.715391 -0.169557     Iris-setosa
2   -2.889820 -0.137346     Iris-setosa
3   -2.746437 -0.311124     Iris-setosa
4   -2.728593  0.333925     Iris-setosa
..        ...       ...             ...
145  1.944017  0.187415  Iris-virginica
146  1.525664 -0.375021  Iris-virginica
147  1.764046  0.078519  Iris-virginica
148  1.901629  0.115877  Iris-virginica
149  1.389666 -0.282887  Iris-virginica

[150 rows x 3 columns]

In [8]:
# n_components=3

# Instantiate PCA
pca = PCA(n_components=3)

# Fit PCA to features
principalComponents = pca.fit_transform(data_PCA)

df = pd.DataFrame(data = principalComponents, 
                  columns = ['PC1','PC2','PC3'])

target = pd.Series(y1['Species'], name='Species')

result_df = pd.concat([df, target], axis=1)
result_df

          PC1       PC2       PC3         Species
0   -2.684207  0.326607 -0.021512     Iris-setosa
1   -2.715391 -0.169557 -0.203521     Iris-setosa
2   -2.889820 -0.137346  0.024709     Iris-setosa
3   -2.746437 -0.311124  0.037672     Iris-setosa
4   -2.728593  0.333925  0.096230     Iris-setosa
..        ...       ...       ...             ...
145  1.944017  0.187415  0.179303  Iris-virginica
146  1.525664 -0.375021 -0.120636  Iris-virginica
147  1.764046  0.078519  0.130784  Iris-virginica
148  1.901629  0.115877  0.722874  Iris-virginica
149  1.389666 -0.282887  0.362318  Iris-virginica

[150 rows x 4 columns]